<a href="https://colab.research.google.com/github/2403a52231-oss/NLP/blob/main/2403A52231_B_09_Ass_6_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task-1

In [ ]:
import nltk
import re
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
import pandas as pd

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
df = pd.read_excel('/content/LDA-Data.xlsx')
print(df)

                             News
0   Virat scored century in match
1            BJP won in elections
2  Bumra took 5 wicket in a match
3  Congress form state government


 Cleaning and Lowercasing

In [ ]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^"\w\s\[\]]', '', text)
    return text

df['cleaned_news'] = df['News'].apply(clean_text)
print(df)

                             News                    cleaned_news
0   Virat scored century in match   virat scored century in match
1            BJP won in elections            bjp won in elections
2  Bumra took 5 wicket in a match  bumra took 5 wicket in a match
3  Congress form state government  congress form state government


## Tokenization

In [ ]:
nltk.download('punkt_tab')
print("Downloaded 'punkt_tab' NLTK resource.")

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


Downloaded 'punkt_tab' NLTK resource.


In [ ]:
from nltk.tokenize import word_tokenize

def tokenize_text(text):
    return word_tokenize(text)

df['tokenized_news'] = df['cleaned_news'].apply(tokenize_text)
print(df)

                             News                    cleaned_news  \
0   Virat scored century in match   virat scored century in match   
1            BJP won in elections            bjp won in elections   
2  Bumra took 5 wicket in a match  bumra took 5 wicket in a match   
3  Congress form state government  congress form state government   

                           tokenized_news  
0     [virat, scored, century, in, match]  
1               [bjp, won, in, elections]  
2  [bumra, took, 5, wicket, in, a, match]  
3     [congress, form, state, government]  


## Stopword Removal


In [ ]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

df['news_without_stopwords'] = df['tokenized_news'].apply(remove_stopwords)
print(df)

                             News                    cleaned_news  \
0   Virat scored century in match   virat scored century in match   
1            BJP won in elections            bjp won in elections   
2  Bumra took 5 wicket in a match  bumra took 5 wicket in a match   
3  Congress form state government  congress form state government   

                           tokenized_news               news_without_stopwords  
0     [virat, scored, century, in, match]      [virat, scored, century, match]  
1               [bjp, won, in, elections]                     [bjp, elections]  
2  [bumra, took, 5, wicket, in, a, match]      [bumra, took, 5, wicket, match]  
3     [congress, form, state, government]  [congress, form, state, government]  


## Lemmatization



In [ ]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatize_text(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

df['lemmatized_news'] = df['news_without_stopwords'].apply(lemmatize_text)
print(df)

                             News                    cleaned_news  \
0   Virat scored century in match   virat scored century in match   
1            BJP won in elections            bjp won in elections   
2  Bumra took 5 wicket in a match  bumra took 5 wicket in a match   
3  Congress form state government  congress form state government   

                           tokenized_news  \
0     [virat, scored, century, in, match]   
1               [bjp, won, in, elections]   
2  [bumra, took, 5, wicket, in, a, match]   
3     [congress, form, state, government]   

                news_without_stopwords                      lemmatized_news  
0      [virat, scored, century, match]      [virat, scored, century, match]  
1                     [bjp, elections]                      [bjp, election]  
2      [bumra, took, 5, wicket, match]      [bumra, took, 5, wicket, match]  
3  [congress, form, state, government]  [congress, form, state, government]  


Rejoin

In [ ]:
def rejoin_text(tokens):
    return ' '.join(tokens)

df['preprocessed_news'] = df['lemmatized_news'].apply(rejoin_text)
print(df)

                             News                    cleaned_news  \
0   Virat scored century in match   virat scored century in match   
1            BJP won in elections            bjp won in elections   
2  Bumra took 5 wicket in a match  bumra took 5 wicket in a match   
3  Congress form state government  congress form state government   

                           tokenized_news  \
0     [virat, scored, century, in, match]   
1               [bjp, won, in, elections]   
2  [bumra, took, 5, wicket, in, a, match]   
3     [congress, form, state, government]   

                news_without_stopwords                      lemmatized_news  \
0      [virat, scored, century, match]      [virat, scored, century, match]   
1                     [bjp, elections]                      [bjp, election]   
2      [bumra, took, 5, wicket, match]      [bumra, took, 5, wicket, match]   
3  [congress, form, state, government]  [congress, form, state, government]   

                preprocessed_new

Bag of words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# Initialize CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the 'preprocessed_news' column
bow_matrix = vectorizer.fit_transform(df['preprocessed_news'])

# Display the Bag of Words matrix (sparse matrix) and feature names
print('Bag of Words Matrix (sparse):')
print(bow_matrix.toarray())
print('\nFeature Names (vocabulary):')
print(vectorizer.get_feature_names_out())

Bag of Words Matrix (sparse):
[[0 0 1 0 0 0 0 1 1 0 0 1 0]
 [1 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 1 0 1]
 [0 0 0 1 0 1 1 0 0 1 0 0 0]]

Feature Names (vocabulary):
['bjp' 'bumra' 'century' 'congress' 'election' 'form' 'government' 'match'
 'scored' 'state' 'took' 'virat' 'wicket']


Bag of words as DataFrame

In [ ]:
bow_df = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer.get_feature_names_out())
display(bow_df)

bjp  bumra  century  congress  election  form  government  match  scored  \
0    0      0        1         0         0     0           0      1       1   
1    1      0        0         0         1     0           0      0       0   
2    0      1        0         0         0     0           0      1       0   
3    0      0        0         1         0     1           1      0       0   

   state  took  virat  wicket  
0      0     0      1       0  
1      0     0      0       0  
2      0     1      0       1  
3      1     0      0       0

Apply LDA

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation

# Instantiate LatentDirichletAllocation model
n_components = 2  # Number of topics
lda_model = LatentDirichletAllocation(n_components=n_components, random_state=42)

# Fit the LDA model to the Bag of Words matrix
lda_model.fit(bow_matrix)
print(f"LDA model fitted with {n_components} components.")

LDA model fitted with 2 components.


In [ ]:
feature_names = vectorizer.get_feature_names_out()
def display_topics(model, feature_names, no_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print(f"Topic {topic_idx}:")
        print(" ".join([feature_names[i] for i in topic.argsort()[:-no_top_words - 1:-1]]))

no_top_words = 5
display_topics(lda_model, feature_names, no_top_words)

Topic 0:
form government congress state election
Topic 1:
match virat century scored took


Topic modeling

In [ ]:
doc_topic_dist = lda_model.transform(bow_matrix)
print("Document-Topic Distribution (probabilities):")
print(doc_topic_dist)

Document-Topic Distribution (probabilities):
[[0.10449107 0.89550893]
 [0.82712002 0.17287998]
 [0.1044911  0.8955089 ]
 [0.89634896 0.10365104]]


In [ ]:
import numpy as np
dominant_topic = np.argmax(doc_topic_dist, axis=1)
print("Dominant topic for each document:")
print(dominant_topic)

Dominant topic for each document:
[1 0 1 0]


In [ ]:
df_results = pd.DataFrame({
    'Original News': df['News'],
    'Dominant Topic': dominant_topic,
    'Topic 0 Probability': doc_topic_dist[:, 0],
    'Topic 1 Probability': doc_topic_dist[:, 1]
})
print("Topic Modeling Results per Document:")
print(df_results)

Topic Modeling Results per Document:
                    Original News  Dominant Topic  Topic 0 Probability  \
0   Virat scored century in match               1             0.104491   
1            BJP won in elections               0             0.827120   
2  Bumra took 5 wicket in a match               1             0.104491   
3  Congress form state government               0             0.896349   

   Topic 1 Probability  
0             0.895509  
1             0.172880  
2             0.895509  
3             0.103651  


TASK-2

In [ ]:
import pandas as pd
data=pd.read_csv('/content/arxiv_data.csv')

display(data.head())

titles  \
0  Survey on Semantic Stereo Matching / Semantic ...   
1  FUTURE-AI: Guiding Principles and Consensus Re...   
2  Enforcing Mutual Consistency of Hard Regions f...   
3  Parameter Decoupling Strategy for Semi-supervi...   
4  Background-Foreground Segmentation for Interio...   

                                           summaries  \
0  Stereo matching is one of the widely used tech...   
1  The recent advancements in artificial intellig...   
2  In this paper, we proposed a novel mutual cons...   
3  Consistency training has proven to be an advan...   
4  To ensure safety in automated driving, the cor...   

                         terms  
0           ['cs.CV', 'cs.LG']  
1  ['cs.CV', 'cs.AI', 'cs.LG']  
2           ['cs.CV', 'cs.AI']  
3                    ['cs.CV']  
4           ['cs.CV', 'cs.LG']

Text Preprocesing: Clean Text, Word Tokenization, stopword removal, lemma,Rejoin




In [ ]:
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

def nltk_preprocessing_pipeline(text):
    # Initialize NLTK tools
    lemmatizer = WordNetLemmatizer()
    stop_words = set(stopwords.words('english'))

    # 1. Preprocess text (from previous steps)
    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    # Remove mentions
    text = re.sub(r'@\w+', '', text)
    # Remove hashtags
    text = re.sub(r'#\w+', '', text)

    text = text.lower()  # Convert to lowercase

    # Remove emojis
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F1E0-\U0001F1FF"  # flags (iOS)
        "\U00002702-\U000027B0"
        "\U000024C2-\U0001F251"
        "]+", flags=re.UNICODE
    )
    text = emoji_pattern.sub(r'', text)

    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)  # Remove special characters
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces

    # 2. Word Tokenization
    tokenized_words = word_tokenize(text)

    # 3. Stopword Removal
    filtered_words = [word for word in tokenized_words if word not in stop_words]

    # 4. Lemmatization
    lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]

    # 5. Rejoin words
    clean_summary = ' '.join(lemmatized_words)

    return clean_summary

print("NLTK preprocessing pipeline function created successfully!")

NLTK preprocessing pipeline function created successfully!


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
data['clean_News'] = data['titles'].apply(nltk_preprocessing_pipeline)
print("\nComparison of previous clean_summaries and new clean_summaries_pipeline (first 5 rows):")
print(data[['clean_News']].head())


Comparison of previous clean_summaries and new clean_summaries_pipeline (first 5 rows):
                                          clean_News
0  survey semantic stereo matching semantic depth...
1  futureai guiding principle consensus recommend...
2  enforcing mutual consistency hard region semis...
3  parameter decoupling strategy semisupervised 3...
4  backgroundforeground segmentation interior sen...


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
# Vectorize the cleaned summaries
count_vectorizer = CountVectorizer(max_df=0.95, min_df=1, stop_words='english')
doc_term_matrix = count_vectorizer.fit_transform(data['clean_News'])

BoW

In [ ]:
import pandas as pd
# Get feature (word) names
feature_names = count_vectorizer.get_feature_names_out()
# Convert sparse matrix to DataFrame
bow_df = pd.DataFrame(doc_term_matrix.toarray(),columns=feature_names)
# Display BoW matrix for top 10 documents
bow_top_10 = bow_df.head(10)
print(bow_top_10)

   01  05mb  09  10  100  1000  10000  100000  1000x  100k  ...  \
0   0     0   0   0    0     0      0       0      0     0  ...   
1   0     0   0   0    0     0      0       0      0     0  ...   
2   0     0   0   0    0     0      0       0      0     0  ...   
3   0     0   0   0    0     0      0       0      0     0  ...   
4   0     0   0   0    0     0      0       0      0     0  ...   
5   0     0   0   0    0     0      0       0      0     0  ...   
6   0     0   0   0    0     0      0       0      0     0  ...   
7   0     0   0   0    0     0      0       0      0     0  ...   
8   0     0   0   0    0     0      0       0      0     0  ...   
9   0     0   0   0    0     0      0       0      0     0  ...   

   zoomtoinpaint  zoonosis  zooplankton  zootuning  zope  zorro  zpd  zscores  \
0              0         0            0          0     0      0    0        0   
1              0         0            0          0     0      0    0        0   
2              0   

Apply LDA

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation

# Initialize and fit LDA model
num_topics = 2
LDA = LatentDirichletAllocation(n_components=num_topics, random_state=42)
LDA.fit(doc_term_matrix)

LatentDirichletAllocation(n_components=2, random_state=42)

In [ ]:
def display_topics(model, feature_names, num_top_words):
    for topic_idx in range(len(model.components_)):
        print(f"\nTopic {topic_idx}:")

        # Get word weights for this topic
        topic_weights = model.components_[topic_idx]

        # Get indices of words sorted by weight (descending)
        sorted_indices = topic_weights.argsort()[::-1]

        # Take top N words
        top_indices = sorted_indices[:num_top_words]

        # Print top words
        for idx in top_indices:
            print(feature_names[idx], end=" ")
        print()

Topic modeling

In [ ]:
# Display top words for each topic
num_top_words = 10
print(f"\nTop {num_top_words} words per topic:")
display_topics(LDA, count_vectorizer.get_feature_names_out(), num_top_words)


Top 10 words per topic:

Topic 0:
learning deep reinforcement representation network using neural image detection time 

Topic 1:
network image graph detection adversarial neural object 3d segmentation using 


In [ ]:
# Assign topics to each document
document_topics = LDA.transform(doc_term_matrix)
data['topic'] = document_topics.argmax(axis=1)

print("\nDataFrame with assigned topics (first 5 rows):")
print(data[['clean_News', 'topic']].head())


DataFrame with assigned topics (first 5 rows):
                                          clean_News  topic
0  survey semantic stereo matching semantic depth...      1
1  futureai guiding principle consensus recommend...      0
2  enforcing mutual consistency hard region semis...      1
3  parameter decoupling strategy semisupervised 3...      0
4  backgroundforeground segmentation interior sen...      1


Task-3

NMF with Kaggle Data and BoW

In [ ]:
from sklearn.decomposition import NMF

nmf = NMF(n_components=2, random_state=42)
nmf.fit(doc_term_matrix)

display_topics(nmf, count_vectorizer.get_feature_names_out(), 10)


Topic 0:
learning reinforcement deep representation using image transfer unsupervised model data 

Topic 1:
network neural graph image using convolutional deep adversarial detection generative 


 NMF with Kaggle Data and TFIDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

# Create TF-IDF matrix
tfidf_vectorizer = TfidfVectorizer(max_df=0.95, min_df=1, stop_words='english')
tfidf_matrix = tfidf_vectorizer.fit_transform(data['clean_News'])

print("TF-IDF Matrix shape:", tfidf_matrix.shape)

# Initialize and fit NMF model
num_topics_nmf = 2
nmf_model_tfidf = NMF(n_components=num_topics_nmf, random_state=42)
nmf_model_tfidf.fit(tfidf_matrix)

print(f"\nNMF model fitted with {num_topics_nmf} components using TF-IDF.")

# Display topics
print("\nTop words per topic (NMF with TF-IDF):")
display_topics(nmf_model_tfidf, tfidf_vectorizer.get_feature_names_out(), 10)

TF-IDF Matrix shape: (51774, 23208)

NMF model fitted with 2 components using TF-IDF.

Top words per topic (NMF with TF-IDF):

Topic 0:
network neural graph convolutional adversarial image generative detection using object 

Topic 1:
learning reinforcement deep representation unsupervised transfer model image using data 


NMF with Sample Data and BoW

In [ ]:
from sklearn.decomposition import NMF

# Instantiate NMF model
num_topics_nmf_sample = 2
nmf_model_sample = NMF(n_components=num_topics_nmf_sample, random_state=42)

# Fit the NMF model to the Bag of Words matrix
nmf_model_sample.fit(bow_matrix)
print(f"NMF model fitted with {num_topics_nmf_sample} components.")

# Display top words for each topic
no_top_words_nmf = 10
print(f"\nTop {no_top_words_nmf} words per topic (NMF with Sample Data BoW):")
display_topics(nmf_model_sample, vectorizer.get_feature_names_out(), no_top_words_nmf)

NMF model fitted with 2 components.

Top 10 words per topic (NMF with Sample Data BoW):

Topic 0:
match virat took scored wicket bumra century bjp election state 

Topic 1:
state form congress government election bjp took virat wicket scored 


NMF with Sample Data and TFIDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

# Create TF-IDF matrix from df['preprocessed_news']
tfidf_vectorizer_df = TfidfVectorizer(max_df=0.95, min_df=1, stop_words='english')
tfidf_matrix_df = tfidf_vectorizer_df.fit_transform(df['preprocessed_news'])

print("TF-IDF Matrix shape for df:", tfidf_matrix_df.shape)

# Initialize and fit NMF model
num_topics_nmf_df = 2
nmf_model_tfidf_df = NMF(n_components=num_topics_nmf_df, random_state=42)
nmf_model_tfidf_df.fit(tfidf_matrix_df)

print(f"\nNMF model fitted for df with {num_topics_nmf_df} components using TF-IDF.")

# Display topics
print("\nTop words per topic (NMF with TF-IDF for df):")
display_topics(nmf_model_tfidf_df, tfidf_vectorizer_df.get_feature_names_out(), 10)

TF-IDF Matrix shape for df: (4, 13)

NMF model fitted for df with 2 components using TF-IDF.

Top words per topic (NMF with TF-IDF for df):

Topic 0:
match bumra wicket took virat scored century state government election 

Topic 1:
election bjp form government state congress took virat wicket scored 
